### ISSUE TITLE
it is not getting the celery settings from my config file

### ISSUE THREAD

**Issue by michaeltcoelho** [Robpol86/Flask-Celery-Helper#10]
Hi there,

I'm facing a strange behavior when executing my celery tasks, Flask-Celery-Helper is not getting my celery settings from the app instance config, here's the code:

settings
```python
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'
```
app.py
```python
def create_app(test=False, **settings):
    """create_app - creates an app instance
    """
    app = Flask('portautos')
    mode = os.environ.get('PORTAUTOS_MODE', 'local')
    app.config.update(settings)

    if test:
        mode = 'test'
    try:
        app.config.from_object('portautos.settings.{}_settings'.format(mode))
    except ImportError:
        pass

    configure_extensions(app)
    return app
```
configure extensions
```python
from .celery import celery

def configure_extensions(app):
    celery.init_app(app)
    return app
```
extension/celery.py
```python
from flask.ext.celery import Celery

celery = Celery()
```

**Comment by Robpol86** [comment]
That is weird. Everything looks correct in your code. I'll investigate this weekend if I can.

**Comment by michaeltcoelho** [comment]
Ok @Robpol86 !

**Comment by Robpol86** [comment]
I'm not sure what's wrong. I haven't had to use this extension since I left my previous job almost 5 months ago and unfortunately I don't have the time to re-learn how to setup a proper Flask and Celery application right now. I couldn't quickly figure out what the issue is.

I'm not sure how you're starting the Celery worker but I bet the way you're starting it doesn't give it the Flask application context. When I last maintained a Flask+Celery app I couldn't use the `celery` command to start the worker.

Check out my example project, maybe you can use it to figure out the cause of the problem.
https://github.com/Robpol86/Flask-Large-Application-Example

You probably want to look at this:
https://github.com/Robpol86/Flask-Large-Application-Example/blob/master/manage.py#L234

Otherwise I'm not sure. Sorry I can't be of more help.

**Comment by wassname** [comment]
I solved this, heres how.
I had by app/__init__.py contstruction my app:
__init__.py
```python
from app.extentions import celery
def create_app(config):
    app = Flask(__name__)
    app.config.from_pyfile(config)
    #... do things
    celery.init_app(app)
    register_blueprints(app)
    return app
```
Then I run celery with
```bash
celery worker -A app
```
But celery didn't inherit the settings so in the root of my module, I created:
celery_entry_point.py
```python
# -*- coding: utf-8 -*-
"""
This file allows celery to import it's config because it creates the app
"""
from extensions import celery
from app import create_app
application  = create_app()
```

Then I run celery with
```bash
celery worker -A app.celery_entry_point
```
So it seems that, unless app is created on import, celery isn't accessing the config.

**Comment by ddkangfu** [comment]
if you use flask-script in your project, you can create a command in manage.py to run celery:
```python
@manager.option('-n', '--name', help='Your app name')
def celeryworker(name):
    celery_args = ['celery', 'worker', '-n', name, '-C', '--autoscale=10,1', '--without-gossip']
    with app.app_context():
        return celery_main(celery_args)
```
call this command in terminal:
```bash
python manage.py celeryworker --name your.task.model.name
```
